using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Rinzler78.NetExtension.SourceGenerators;

/// <summary>
/// Incremental source generator that produces public observable properties from fields
/// annotated with <c>[ObservableProperty]</c> in partial classes.
/// </summary>
[Generator]
public sealed class ObservablePropertyGenerator : IIncrementalGenerator
{
    private const string AttributeFullName =
        "Rinzler78.NetExtension.Observable.ObservablePropertyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var fields = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is FieldDeclarationSyntax f && f.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetFieldInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        context.RegisterSourceOutput(fields.Collect(), static (spc, all) => Emit(spc, all));
    }

    private static FieldInfo? GetFieldInfo(GeneratorSyntaxContext ctx)
    {
        var fieldDecl = (FieldDeclarationSyntax)ctx.Node;
        if (fieldDecl.Parent is not ClassDeclarationSyntax classDecl)
            return null;
        if (!classDecl.Modifiers.Any(SyntaxKind.PartialKeyword))
            return null;

        foreach (var variable in fieldDecl.Declaration.Variables)
        {
            if (ctx.SemanticModel.GetDeclaredSymbol(variable) is not IFieldSymbol field)
                continue;

            var attr = field.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == AttributeFullName);
            if (attr is null)
                continue;

            string? explicitName = attr.ConstructorArguments.Length > 0
                ? attr.ConstructorArguments[0].Value as string
                : null;

            string propertyName = explicitName ?? DerivePropertyName(field.Name);
            if (string.IsNullOrEmpty(propertyName))
                continue;

            return new FieldInfo(
                field.Name,
                propertyName,
                field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                field.ContainingType,
                field.ContainingType.ContainingNamespace?.ToDisplayString() ?? string.Empty);
        }

        return null;
    }

    private static void Emit(
        SourceProductionContext spc,
        System.Collections.Immutable.ImmutableArray<FieldInfo> allFields)
    {
        foreach (var group in allFields.GroupBy(f => f.ContainingType, SymbolEqualityComparer.Default))
        {
            var type = (INamedTypeSymbol)group.Key!;
            var ns = group.First().Namespace;
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine($"namespace {ns};");
                sb.AppendLine();
            }

            sb.Append(Accessibility(type));
            if (type.IsAbstract) sb.Append("abstract ");
            if (type.IsSealed) sb.Append("sealed ");
            sb.AppendLine($"partial class {type.Name}");
            sb.AppendLine("{");

            foreach (var f in group)
            {
                sb.AppendLine($"    /// <inheritdoc cref=\"{f.FieldName}\"/>");
                sb.AppendLine($"    public {f.TypeName} {f.PropertyName}");
                sb.AppendLine("    {");
                sb.AppendLine($"        get => {f.FieldName};");
                sb.AppendLine($"        set => SetProperty(ref {f.FieldName}, value);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");

            string hint = $"{ns}_{type.Name}_ObservableProperties.g.cs".Replace(".", "_");
            spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private static string Accessibility(INamedTypeSymbol t) => t.DeclaredAccessibility switch
    {
        Microsoft.CodeAnalysis.Accessibility.Public => "public ",
        Microsoft.CodeAnalysis.Accessibility.Internal => "internal ",
        _ => string.Empty,
    };

    /// <summary>
    /// Strips leading underscores and the <c>m_</c> prefix, then capitalises the first letter.
    /// </summary>
    public static string DerivePropertyName(string fieldName)
    {
        if (string.IsNullOrEmpty(fieldName)) return fieldName;
        var s = fieldName.TrimStart('_');
        if (s.StartsWith("m_") && s.Length > 2) s = s.Substring(2);
        if (string.IsNullOrEmpty(s)) return fieldName;
        return char.ToUpper(s[0]) + s.Substring(1);
    }

    private sealed class FieldInfo
    {
        public FieldInfo(string fieldName, string propertyName, string typeName,
            INamedTypeSymbol containingType, string ns)
        {
            FieldName = fieldName; PropertyName = propertyName; TypeName = typeName;
            ContainingType = containingType; Namespace = ns;
        }
        public string FieldName { get; }
        public string PropertyName { get; }
        public string TypeName { get; }
        public INamedTypeSymbol ContainingType { get; }
        public string Namespace { get; }
    }
}
