<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Rinlzer78.NetExtension</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.Build.Packaging" Version="0.2.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Json\" />
    <None Remove="Newtonsoft.Json" />
    <None Remove="Objects\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Json\" />
    <Folder Include="Objects\" />
  </ItemGroup>
</Project>
